# Generated by Django 4.2 on 2023-08-13 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Город')),
                ('region', models.CharField(choices=[('Aşgabat', 'Aşgabat'), ('Mary', 'Mary'), ('Lebap', 'Lebap'), ('Daşoguz', 'Daşoguz'), ('Balkan', 'Balkan'), ('Ahal', 'Ahal')], default='Aşgabat', max_length=16)),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255, verbose_name='Модель автомобиля')),
                ('vehicle_type', models.CharField(choices=[('Ýolagçy awtoulag', 'Ýolagçy awtoulag'), ('Ýük awtoulag', 'Ýük awtoulag')], default='Ýolagçy awtoulag', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='transports/')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_transport', to=settings.AUTH_USER_MODEL, verbose_name='Пользоатель')),
            ],
            options={
                'verbose_name': 'Транспорт',
                'verbose_name_plural': 'Транспорты',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaving_time', models.DateTimeField(blank=True, null=True, verbose_name='Время')),
                ('capacity', models.IntegerField(blank=True, default=4, null=True, verbose_name='Число Людей')),
                ('is_intercity', models.BooleanField(default=False, verbose_name='Внутригородний')),
                ('is_onway', models.BooleanField(default=False, verbose_name='Попутный')),
                ('description', models.CharField(max_length=255, verbose_name='Доп инфо')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_from_location', to='transport.locations', verbose_name='Поездка из')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_to_location', to='transport.locations', verbose_name='Поездка в')),
                ('transport_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_transport', to='transport.transport', verbose_name='Транспорт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_trip', to=settings.AUTH_USER_MODEL, verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Поездка',
                'verbose_name_plural': 'Поездки',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255, verbose_name='Титул')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='Подробнее')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('user_commented', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_commented_comments', to=settings.AUTH_USER_MODEL, verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Коммент',
                'verbose_name_plural': 'Комменты',
            },
        ),
    ]
