# Generated by Django 4.2 on 2023-08-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_trip_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='cargo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='passanger',
            field=models.BooleanField(default=True),
        ),
    ]
