# Generated by Django 4.2 on 2023-09-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_trip_cargo_trip_passanger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Доп инфо'),
        ),
    ]
